# Generated by Django 2.2.3 on 2019-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_auto_20190703_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
