# Generated by Django 2.2.3 on 2019-07-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20190725_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
