# Generated by Django 2.2.3 on 2019-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='configuration',
            field=models.TextField(default='{}'),
        ),
    ]
