# Generated by Django 2.2.3 on 2019-08-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_auto_20190829_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
