# Generated by Django 2.2.3 on 2019-08-29 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_type', models.BooleanField(default=0)),
                ('severity_level', models.CharField(blank=True, max_length=10, null=True)),
                ('notification', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=0)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
