# Generated by Django 2.2.4 on 2019-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190918_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='no_visits',
            field=models.IntegerField(default=0),
        ),
    ]
